# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author:
name: "ECE 6960: Data Center Networking Systems"
title: Data Center Networking Systems
email:
description: >
  ECE 6960 - Data Center Networking Systems - Cornell University - Fall 2025
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: "https://www.csl.cornell.edu" # the base hostname & protocol for your site
# url: "lockhome.local" # the base hostname & protocol for your site -> for debug
baseurl: "/~jiaxinl/ece6960/fa25/" # the subpath of your site, e.g. /blog/


# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username:
google_analytics:
youtube_channel:
rss: # notes rss

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Course Notes
blog_description: The notes written by students and edited by instructors

# Pagination
paginate: 10
permalink: /notes/:title/
paginate_path: /notes/page:num/

text:
  pagination:
    newer: "Newer"
    older: "Older"

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons: true
enable_anchorjs: true
enable_latexjs: true
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/

announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages"]
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - "*.sh"

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jemoji
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

theme: jekyll-theme-slate

